# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 97d9daccf6e953ac0d6cd80aee5643399202524cf194c8cb1d60580b4c3b55fd75fc659b7f6030f48003f08a36944bb922f254405ceaa2ddd5c1df278356a8dd

test:
  secret_key_base: 79db837043c5a54589f415d4b96c561e20bfe5af8486f85ab211d21ac43084f678cff7bd32a96a5cad11082dda870fd74552ed41f1f4b301b112b808f007c388

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
